-- 0004: switch embeddings to a 384-dim local model (fastembed BGE-small).
--
-- The previous vectors were produced by the 'fake' dev provider, so they carry no
-- semantic meaning and retrieval was effectively random. They must be regenerated at
-- the new dimension. We drop the HNSW index (can't alter an indexed vector column),
-- clear the placeholder rows, shrink the column to 384 dims, rebuild the index, and
-- mark every source 'pending' so the re-ingest step regenerates real embeddings.
DROP INDEX IF EXISTS chunks_embedding_hnsw_idx;

-- Placeholder-embedded data; regenerated by re-ingestion. TRUNCATE (not DELETE) so it
-- isn't filtered by RLS and resets cleanly.
TRUNCATE chunks, documents;

ALTER TABLE chunks ALTER COLUMN embedding TYPE vector(384);

CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw_idx
  ON chunks USING hnsw (embedding vector_cosine_ops);

UPDATE sources SET status = 'pending', error = NULL, updated_at = now();
